"""empty message

Revision ID: 25cd17d00a81
Revises: 76b743b2b43d
Create Date: 2022-06-09 20:56:00.500918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cd17d00a81'
down_revision = '76b743b2b43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'date')
    # ### end Alembic commands ###
