"""empty message

Revision ID: e49f2ae65e25
Revises: 3958ebbea20b
Create Date: 2022-06-07 08:48:15.403742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49f2ae65e25'
down_revision = '3958ebbea20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'content',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'content',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
