"""empty message

Revision ID: 1d05ad34e5f6
Revises: df68f82c5a8d
Create Date: 2022-06-06 20:51:04.763594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d05ad34e5f6'
down_revision = 'df68f82c5a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('content', sa.String(length=255), nullable=True))
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'content')
    # ### end Alembic commands ###
