"""empty message

Revision ID: 30aa35bb8ec2
Revises: 1d05ad34e5f6
Create Date: 2022-06-07 06:41:40.070933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aa35bb8ec2'
down_revision = '1d05ad34e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('properties', sa.Column('long', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'long')
    op.drop_column('properties', 'lat')
    # ### end Alembic commands ###
