"""empty message

Revision ID: 86fb3e3ea7e8
Revises: e49f2ae65e25
Create Date: 2022-06-08 14:16:45.065457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86fb3e3ea7e8'
down_revision = 'e49f2ae65e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date', sa.String(length=50), nullable=False))
    op.add_column('appointments', sa.Column('time', sa.String(length=50), nullable=False))
    op.drop_column('appointments', 'appointment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'time')
    op.drop_column('appointments', 'date')
    # ### end Alembic commands ###
