"""empty message

Revision ID: f9bcf1be743c
Revises: 5a2735aa7b04
Create Date: 2022-06-14 09:22:16.745386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bcf1be743c'
down_revision = '5a2735aa7b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_areas', 'zip',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_areas', 'zip',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
