"""empty message

Revision ID: 8b7388278692
Revises: ffdc0a98111c
Create Date: 2022-06-06 15:41:40.717892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7388278692'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('agent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('license_num', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('broker_license', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('office', sa.String(length=100), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'office')
    op.drop_column('users', 'broker_license')
    op.drop_column('users', 'photo')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'license_num')
    op.drop_column('users', 'agent')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
