"""empty message

Revision ID: 3958ebbea20b
Revises: 30aa35bb8ec2
Create Date: 2022-06-07 08:33:25.184894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3958ebbea20b'
down_revision = '30aa35bb8ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('front_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'front_img')
    # ### end Alembic commands ###
