"""empty message

Revision ID: 84446ce6802e
Revises: 25cd17d00a81
Create Date: 2022-06-10 14:21:33.138361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84446ce6802e'
down_revision = '25cd17d00a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('long', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'states', ['long'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'states', type_='unique')
    op.drop_column('states', 'long')
    # ### end Alembic commands ###
