"""empty message

Revision ID: 76b743b2b43d
Revises: 86fb3e3ea7e8
Create Date: 2022-06-08 14:37:27.592708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b743b2b43d'
down_revision = '86fb3e3ea7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
